Moved settings to the top of the script

diff --git a/appenv9 b/appenv9
--- a/appenv9
+++ b/appenv9
@@ -1,16 +1,16 @@
 #!/usr/bin/bash
 
-if [ $# -eq 0 ]; then
-	echo "[ERROR] No name specified"
-	exit 1
-fi
-
 PREFIX=django-
 DJANGO_VERSION=1.6.5
 PYTHON_VERSION=2.7
 
 AUTHOR_NAME=$(git config user.name)
 AUTHOR_EMAIL=$(git config user.email)
+
+if [ $# -eq 0 ]; then
+	echo "[ERROR] No name specified"
+	exit 1
+fi
 
 NAME=$1
 SAFE_NAME="${NAME//-/_}"
